-- =========================================================================
-- Banjara menu seed — generated by scripts/extract_menu.py
-- Idempotent: wipes menu tables then reseeds.
-- =========================================================================

begin;

truncate table menu_items, menu_categories restart identity cascade;

with c as (insert into menu_categories (name, slug, sort_order) values ('Soups', 'soups', 0) returning id)
insert into menu_items (category_id, name, description, price, is_veg, sort_order) values
((select id from c), 'Mr Lee''s Manchow', 'Crispy noodles, crispy vegetables', 375.00, true, 0),
((select id from c), 'It''s Hot, It''s Sour', 'Toban Tofu, Shiitake', 375.00, true, 1),
((select id from c), 'Miso Sweet Corn Soup', 'Bamboo & bok choy', 375.00, true, 2),
((select id from c), 'Kashmiri Themthuk', 'Chilli, Butter Bean, Crispy Tofu, Bread', 375.00, true, 3),
((select id from c), 'Lemon Coriander', 'Kalamique, Shiitake, Chilli Crunch', 375.00, true, 4),
((select id from c), 'Asian Magic Broth', 'Tofu, Kelp, Chilli Labneh', 375.00, true, 5),
((select id from c), 'Roasted Tomato Basil', 'Cheddar Crouton', 395.00, true, 6),
((select id from c), 'Malaysian Thupka Soup', 'Noodles, Jasmine with all hits', 395.00, true, 7),
((select id from c), 'Brocolli Almond Cheddar', NULL, 395.00, true, 8),
((select id from c), 'Mexican Tortilla Soup', 'Crispy Tortilla, Peppers', 395.00, true, 9),
((select id from c), 'Corn Palak Shorba', 'Toasted almond quinoa', 395.00, true, 10),
((select id from c), 'DIY Burmese Khao Suey', 'Noodles, Crispy noodles, garnishes, thick brown gravy', 575.00, true, 11);

with c as (insert into menu_categories (name, slug, sort_order) values ('Salads', 'salads', 1) returning id)
insert into menu_items (category_id, name, description, price, is_veg, sort_order) values
((select id from c), 'Grilled Caesar', 'Grilled Butter Chicken, Parmesan Dressing', 475.00, false, 0),
((select id from c), 'Asian Crunchy Salad', 'Crispy Noodles, Peanut Butter, Tofu', 475.00, true, 1),
((select id from c), 'Caprese Burrata', 'Tomatoes, sweet, Pistachio Pesto, Balsamic, Crispy Basil', 525.00, true, 2),
((select id from c), 'Mexican Corn and Avocado', 'Roasted Corn, Avocado, Chipotle Cheese', 525.00, true, 3);

with c as (insert into menu_categories (name, slug, sort_order) values ('Chaat Party', 'chaat-party', 2) returning id)
insert into menu_items (category_id, name, description, price, is_veg, sort_order) values
((select id from c), 'Chilli Passionfruit Pani Puri', 'Passionfruit shots, khatta pani', 455.00, true, 0),
((select id from c), 'Aloo Tikki Canvas', 'Fresh herbs, paneer curry, dal chutneys', 475.00, true, 1),
((select id from c), '3 Patta Chaat', 'Sweet, tangy, kasoori tea', 475.00, true, 2),
((select id from c), 'Bombay Chinese Bhel', 'Crispy noodles, schezwan chutneys', 475.00, true, 3),
((select id from c), 'Dim-Sum Chaat', 'Fried Dim-sums, Chutneys', 475.00, true, 4),
((select id from c), 'Ying Yang Dahi Puri', 'Smoked Tofu, shiitake chutneys', 475.00, true, 5),
((select id from c), 'Layered Papdi Pullover Chaat', 'Sweet Corn, potato, masala chutney', 495.00, true, 6),
((select id from c), 'Mexican Chaat', 'Crispy tortillas, anardana, chutneys', 495.00, true, 7),
((select id from c), 'Avocado Sev Puri Platter', '(8 pcs)', 525.00, true, 8),
((select id from c), 'Smoked Burrata Lotus Stem Chaat', 'Spicy tamarind compote, anti-dhuniya sev', 545.00, true, 9);

with c as (insert into menu_categories (name, slug, sort_order) values ('Banjara Sharing Plates', 'banjara-sharing-plates', 3) returning id)
insert into menu_items (category_id, name, description, price, is_veg, sort_order) values
((select id from c), 'Chilli Cheese Pull Apart Bread', 'Fresh Chilli Mozzarella, Garlic Butter, Herbs', 995.00, true, 0),
((select id from c), 'Bruschetta Board', 'Roasted Peppers, Cherry Tomato Relish', 995.00, true, 1),
((select id from c), 'Hummus Board', 'Classic hummus, Roasted Red Hummus, Fluffy Pita, Burnt Labneh', 995.00, true, 2),
((select id from c), 'Tandoori Platter', 'Hariyali Kebab, Calcutta Club Bharwan, Kesari Paneer Tikka, Mushroom Galouti, Cheesy Kebab', 1275.00, true, 3);

with c as (insert into menu_categories (name, slug, sort_order) values ('Indian Favourites', 'indian-favourites', 4) returning id)
insert into menu_items (category_id, name, description, price, is_veg, sort_order) values
((select id from c), 'Maharashtrian Kanda Bhaji', 'Sliced Onion, Besan Batter, Chutneys', 495.00, true, 0),
((select id from c), 'Kashmiri Nadru Monje', 'Lotus root, jalapeno, crispy masala, hiramanth', 495.00, true, 1),
((select id from c), 'Rajma Shami Pao', 'Rajmah patty, mince chilli cream', 495.00, true, 2),
((select id from c), 'Kungpao Manchurian', 'Cottage cheese, black bean chilli, peanuts', 525.00, true, 3),
((select id from c), 'Paan Dahi Kebab', 'Spiced Makhanwala, mint tulsi chutney', 545.00, true, 4),
((select id from c), 'Cheesy Hara Akhrot Kebab', 'Herb cheese, walnuts', 545.00, true, 5),
((select id from c), 'Railway Beetroot Outlet', 'Classic sauce, Beetroot Patty', 575.00, true, 6),
((select id from c), 'Makhani Shots', 'Dal makhani, cheese minis', 595.00, true, 7);

with c as (insert into menu_categories (name, slug, sort_order) values ('International Favourites', 'international-favourites', 5) returning id)
insert into menu_items (category_id, name, description, price, is_veg, sort_order) values
((select id from c), 'Maggi Masala Fries', 'Chilli garlic, schezwan mayo', 395.00, true, 0),
((select id from c), 'Dirty Nachos', 'Baked cheese, tomato salsa, sour cream', 455.00, true, 1),
((select id from c), 'Mexican Cheese Bombs', 'Jalapeño cheese, ancho chilli dip', 525.00, true, 2),
((select id from c), 'Tiffin Potato Sliders', 'Mini pav, aloo patty', 525.00, true, 3),
((select id from c), 'Thai Basil Spring Rolls', 'Sweet chilli, rice paper basil', 545.00, true, 4),
((select id from c), 'Wok Tossed Waterchestnuts', 'Szechuan green vegetable', 545.00, true, 5),
((select id from c), 'Kung Pao Lotus Stem', 'Roasted cashew, chilli-soy', 545.00, true, 6),
((select id from c), 'Firecracker Paneer Katifi', 'Shredded wheatgrass paste, sriracha', 545.00, true, 7),
((select id from c), 'Sizzling Paneer Chilly', NULL, 545.00, true, 8),
((select id from c), 'Sundried Tomato & Pesto Aranchini', 'Semi mozzarella, mint and jalapeño dip', 545.00, true, 9),
((select id from c), 'Salt and Pepper Vegetables', NULL, 545.00, true, 10),
((select id from c), 'Muromachi Crispy Vegetables', 'Stir fried batter-fried garlic', 545.00, true, 11);

with c as (insert into menu_categories (name, slug, sort_order) values ('Dimsums & Baos', 'dimsums-baos', 6) returning id)
insert into menu_items (category_id, name, description, price, is_veg, sort_order) values
((select id from c), 'Delhi Haat Ke Momos', NULL, 575.00, true, 0),
((select id from c), 'Vada Bao', NULL, 595.00, true, 1),
((select id from c), 'Cream Cheese Water Chestnut', NULL, 625.00, true, 2),
((select id from c), 'Paneer Chilli Bao', NULL, 625.00, true, 3),
((select id from c), 'Teriyaki Vegetable Bao', NULL, 625.00, true, 4),
((select id from c), 'Wontons in Chilli Broth', NULL, 645.00, true, 5);

with c as (insert into menu_categories (name, slug, sort_order) values ('Tikkis & Kebabs', 'tikkis-kebabs', 7) returning id)
insert into menu_items (category_id, name, description, price, is_veg, sort_order) values
((select id from c), 'Dilli-6 Seekh Kebab', 'Lamb mince, cilantro, ginger, onion', 595.00, false, 0),
((select id from c), 'Calcutta Club Bharwan Aloo', 'Rohan Kebab, dum-stuffed potato', 595.00, true, 1),
((select id from c), 'Kesari Panner Tikka', 'Saffron Marinated, Raisin Chutney, Tamarind', 625.00, true, 2),
((select id from c), 'Amritsari Paneer Tikka', 'Spiced yogurt marination, mint chutney', 625.00, true, 3),
((select id from c), 'Mushroom and Cheese Galouti', 'Shahi, porcini, spicy pineapple chutney', 625.00, true, 4),
((select id from c), 'Awadhi Seekh Kebab', 'Garlic, Ajwain, Saunth Ki Sabzi', 625.00, true, 5),
((select id from c), 'Hariyali Soya Seekh', 'Moist, Djondni, Coconut', 625.00, true, 6),
((select id from c), 'Achari Soya Chaap', 'Whipped Tofu, peanut chutney', 625.00, true, 7),
((select id from c), 'Paneer Tikka Three Ways', 'Tandoori, Malabari, Afghani, Kali Mirch; Green Apple Mint Relish', 645.00, true, 8),
((select id from c), 'Pahadgani Paneer', 'Green apple mint relish, masala onion', 645.00, true, 9),
((select id from c), 'Bharwan Rajputana Paneer', 'Nut stuffed, spicy mint chutney', 645.00, true, 10),
((select id from c), 'Mustard Malai Brocolli', 'Crispy garlic, pista vinaigrette, mango pickle', 675.00, true, 11);

with c as (insert into menu_categories (name, slug, sort_order) values ('Wood Fired Pizza', 'wood-fired-pizza', 8) returning id)
insert into menu_items (category_id, name, description, price, is_veg, sort_order) values
((select id from c), 'Cheese Overload', 'Cheddar, cream, pizza cheese', 695.00, true, 0),
((select id from c), 'Margherita', 'Mozzarella, basil', 695.00, true, 1),
((select id from c), 'Rainbow', 'Peppers, mushrooms, olives, onions', 695.00, true, 2),
((select id from c), 'Hot Head', 'Ajvar, chilli, crunchy jalapeno, corn', 695.00, true, 3),
((select id from c), 'Pesto Burrata', 'Walnut pesto, blistered cherry tomatoes', 725.00, true, 4),
((select id from c), 'Tandoori Paradise', 'Paneer tikka, mushroom, capsicum, green chilli, paneer', 745.00, true, 5);

with c as (insert into menu_categories (name, slug, sort_order) values ('Sushi', 'sushi', 9) returning id)
insert into menu_items (category_id, name, description, price, is_veg, sort_order) values
((select id from c), '4 Treasure Roll', 'Carrot, Cucumber, Avo, Cream Tofu', 595.00, true, 0),
((select id from c), 'Phily Cheese California Roll', 'Cream Cheese, Cucumber, Crispy Chip', 595.00, true, 1),
((select id from c), 'Spicy Avocado Roll', 'Jalapeño, Avocado, Toasted Sesame Seeds, Furikake', 625.00, true, 2),
((select id from c), 'Asparagus Tempura', 'Crispy Tempura, Wasabi Aioli', 625.00, true, 3);

with c as (insert into menu_categories (name, slug, sort_order) values ('Little Mexico!!!!', 'little-mexico', 10) returning id)
insert into menu_items (category_id, name, description, price, is_veg, sort_order) values
((select id from c), 'Roasted Peppers and Cheese Quesadillas', 'Red Peppers, Jack Cheese, Chipotle Cream', 595.00, true, 0),
((select id from c), 'Mexican Hot Pot', 'Rajma, Cheese Sauce, Crinkle Sauce', 625.00, true, 1),
((select id from c), 'Nachos Tasting Platter', 'Cheese, Salsa, Guac, Sour Cream, Ancho Guacamole, Sour Cream', 625.00, true, 2);

with c as (insert into menu_categories (name, slug, sort_order) values ('Pasta''s & Rissoto', 'pasta-s-rissoto', 11) returning id)
insert into menu_items (category_id, name, description, price, is_veg, sort_order) values
((select id from c), 'Spaghetti Aglio Olio', 'Fresh Garlic, Parsley', 625.00, true, 0),
((select id from c), 'Alfredo Spaghetti', 'Parma Herb Crumbles', 645.00, true, 1),
((select id from c), 'Chilli Penne Arrabiata', 'Tomato, Garlic, Olives', 645.00, true, 2),
((select id from c), 'Spaghetti Rose', 'Carbonara Cream, Crushed Tomato, Crispy Basil', 645.00, true, 3),
((select id from c), 'Four Cheese Penne', 'Cheddar, Parmesan, Cream Cheese, Bocconcini', 695.00, true, 4),
((select id from c), 'Quattro Fromage Mac and Cheese', 'Béchamel, Mozzarella, Gouda, Parmesan; Option — Pineapple', 695.00, true, 5),
((select id from c), 'Layered Vegetable Lasagna', NULL, 695.00, true, 6),
((select id from c), 'Cream and Saffron Rissoto', 'Herb Crumbles, Basil', 725.00, true, 7),
((select id from c), 'Asparagus Green Pea Rissoto', 'Ricotta Parmesan, Crumble', 725.00, true, 8),
((select id from c), 'Sundried Tomato Rissoto', 'Bocconcini, Black Olives', 725.00, true, 9);

with c as (insert into menu_categories (name, slug, sort_order) values ('Sizzler''s Around the World', 'sizzler-s-around-the-world', 12) returning id)
insert into menu_items (category_id, name, description, price, is_veg, sort_order) values
((select id from c), 'Mumbai Tawa Pulao', 'Basmati, Street Pavs, Tawa, Fried vegetables', 785.00, true, 0),
((select id from c), 'Oriental Hot Garlic Paneer', 'Paneer, Rice mushrooms, stir fried vegetables', 825.00, true, 1),
((select id from c), 'Tex Mex Pot Rice', 'Mexican rice, Nacho, Chinese sauce, smashed cream sauce', 825.00, true, 2),
((select id from c), 'Veg Stroganoff Sizzler', 'Sautéed Vegetables, buttered rice', 825.00, true, 3);

with c as (insert into menu_categories (name, slug, sort_order) values ('From the Wok', 'from-the-wok', 13) returning id)
insert into menu_items (category_id, name, description, price, is_veg, sort_order) values
((select id from c), 'Tibetan Vegetable Stir Fry', 'Fresh vegetables, Fresh green sauce', 695.00, true, 0),
((select id from c), 'Cottage Cheese Shanghai', 'Chilli peppers, fried capsicum', 695.00, true, 1),
((select id from c), 'Classic Cottage Cheese Manchurian', 'Yuen, celery, bean sprouts', 695.00, true, 2),
((select id from c), 'Mapo Tofu', 'Mala Sichuan Szechuan', 725.00, true, 3),
((select id from c), 'Stir Fried Waterchestnut Sichaun', 'Fried garlic, cashews', 725.00, true, 4),
((select id from c), 'Hot Garlic Brocolli and Asparagus', 'Fried garlic, soy, butter', 725.00, true, 5),
((select id from c), 'Red Malaysian Curry', 'Jasmine rice, kaffir lime', 725.00, true, 6),
((select id from c), 'Thai Green / Red Curry', 'Jasmine rice, kaffir lime', 725.00, true, 7);

with c as (insert into menu_categories (name, slug, sort_order) values ('Rice & Noodles', 'rice-noodles', 14) returning id)
insert into menu_items (category_id, name, description, price, is_veg, sort_order) values
((select id from c), 'Fire Dragon Rice', 'Dragon, Szechuan, Smoked garlic', 445.00, true, 0),
((select id from c), 'Burnt Garlic Fried Rice', 'Fried garlic', 445.00, true, 1),
((select id from c), 'Dynamite Fried Rice', 'Crispy lao, lemongrass chilli sauce', 455.00, true, 2),
((select id from c), 'Hong Kong Noodles', 'Sautons, Crispy garlic', 455.00, true, 3),
((select id from c), 'Hakka Noodles', 'Szechuan, Crispy Garlic', 455.00, true, 4),
((select id from c), 'Pad Thai', 'Roasted peanut and soy peanut chilli sauce', 475.00, true, 5),
((select id from c), '3 Chilli Garlic Noodles', 'Crushed peppers, crushed peanuts', 475.00, true, 6),
((select id from c), 'Truffle Edamame Fried Rice', 'Crispy leeks, tatsoi corn', 495.00, true, 7);

with c as (insert into menu_categories (name, slug, sort_order) values ('Khazana — Paneer Mains', 'khazana-paneer-mains', 15) returning id)
insert into menu_items (category_id, name, description, price, is_veg, sort_order) values
((select id from c), 'Kali Mirch Paneer Kadhai', 'Red chillies, onion', 625.00, true, 0),
((select id from c), 'Highway Style Paneer Bhurji', 'Capsicum, tomatoes, green masala', 625.00, true, 1),
((select id from c), 'Paneer Pepper Khurchan', 'Peppers, onion', 645.00, true, 2),
((select id from c), 'Smoked Pepper Paneer', NULL, 655.00, true, 3),
((select id from c), 'BBQ Paneer Masala', 'Habanero chilli oil', 655.00, true, 4),
((select id from c), 'Hari Mirch Paneer', NULL, 655.00, true, 5),
((select id from c), 'Sizzling Tawa Paneer', 'Tossed peppers, drumstick masala', 675.00, true, 6),
((select id from c), 'Paneer Pakiza', 'Tomato Gravy, Chilli Kewda', 675.00, true, 7),
((select id from c), 'Cottage Cheese Lababdar', NULL, 675.00, true, 8),
((select id from c), 'Cheese Butter Masala', 'Makhani Cream, Yogurt Oil', 675.00, true, 9);

with c as (insert into menu_categories (name, slug, sort_order) values ('Khazana — Subz Mains', 'khazana-subz-mains', 16) returning id)
insert into menu_items (category_id, name, description, price, is_veg, sort_order) values
((select id from c), 'Homestyle Jeera Aloo', 'Tempered cumin', 595.00, true, 0),
((select id from c), 'Subz Nizami Handi', 'Cashew cashews, milk oil', 625.00, true, 1),
((select id from c), 'Amritsari Subz Kadhai', 'Rava onion, fried masala', 625.00, true, 2),
((select id from c), 'Subz Lucknowi Handi', 'Kewra, Saffron, Yogurt, Roquette', 625.00, true, 3),
((select id from c), 'Sizzling Hyderabadi Subzi', 'Roasted chilli, chilli oil', 635.00, true, 4),
((select id from c), 'Himalayan Subz Handi', 'Smoked tomato, onion paste', 645.00, true, 5),
((select id from c), 'Exotic Vegetable Khurchan', 'Peppers, onion, chilli oil', 645.00, true, 6);

with c as (insert into menu_categories (name, slug, sort_order) values ('Khazana — Kofta & Chaap', 'khazana-kofta-chaap', 17) returning id)
insert into menu_items (category_id, name, description, price, is_veg, sort_order) values
((select id from c), 'Spinach and Corn Kofta', 'Bottle gourd, cashew cream', 625.00, true, 0),
((select id from c), 'Bhuna Soya Chaap', 'Bamboo stem, chilli oil', 625.00, true, 1),
((select id from c), 'Banjara Malai Kofta', 'Fresh garlic, makhani cream', 645.00, true, 2),
((select id from c), 'Mini Cheese Kofta', 'Soft, al dente', 645.00, true, 3),
((select id from c), 'Brocolli and Corn Kofta', 'Kurkure, desi filled garlic', 655.00, true, 4);

with c as (insert into menu_categories (name, slug, sort_order) values ('Dal & Lentils', 'dal-lentils', 18) returning id)
insert into menu_items (category_id, name, description, price, is_veg, sort_order) values
((select id from c), 'Dal Tadka', 'Tarka yellow arhar', 595.00, true, 0),
((select id from c), 'Dal Palak', 'Tempered spinach, yellow lentil', 595.00, true, 1),
((select id from c), '24Hr Dal Makhani', 'Smoked lentil, butter', 655.00, true, 2);

with c as (insert into menu_categories (name, slug, sort_order) values ('Rice', 'rice', 19) returning id)
insert into menu_items (category_id, name, description, price, is_veg, sort_order) values
((select id from c), 'Steam Rice', NULL, 355.00, true, 0),
((select id from c), 'Ghee Jeera Bhaat', NULL, 375.00, true, 1),
((select id from c), 'Dal Palak Khichdi', NULL, 425.00, true, 2),
((select id from c), 'Dal Khichdi', NULL, 425.00, true, 3),
((select id from c), 'Aamchi Tawa Pulao', NULL, 455.00, true, 4),
((select id from c), 'Rakabdar''s Biryani', NULL, 575.00, true, 5),
((select id from c), 'Lucknowi Biryani', NULL, 575.00, true, 6),
((select id from c), 'Hyderabadi Biryani', NULL, 575.00, true, 7);

with c as (insert into menu_categories (name, slug, sort_order) values ('Breads', 'breads', 20) returning id)
insert into menu_items (category_id, name, description, price, is_veg, sort_order) values
((select id from c), 'Tandoori Roti', 'Smoked Butter | Ghee Rogan', 175.00, true, 0),
((select id from c), 'Naan — Chilli Garlic | Masala Butter', NULL, 225.00, true, 1),
((select id from c), 'Laccha Paratha Pudina | Mirchi', NULL, 225.00, true, 2),
((select id from c), 'Warqi Paratha', NULL, 225.00, true, 3),
((select id from c), 'Black Pepper Churchur Naan', NULL, 245.00, true, 4),
((select id from c), 'Kulchettes Cheese | Green | Aloo Pyaaz', NULL, 245.00, true, 5),
((select id from c), 'Sundried Tomato Mozzarella Kulcha', NULL, 275.00, true, 6);

with c as (insert into menu_categories (name, slug, sort_order) values ('Sides', 'sides', 21) returning id)
insert into menu_items (category_id, name, description, price, is_veg, sort_order) values
((select id from c), 'Masala Papad (1 pc)', NULL, 155.00, true, 0),
((select id from c), 'Butter Milk', NULL, 195.00, true, 1),
((select id from c), 'Papadum, Homemade Chutney Platter', NULL, 245.00, true, 2),
((select id from c), 'Anar Ka Raita', NULL, 245.00, true, 3),
((select id from c), 'Pudina Walnut Raita', NULL, 245.00, true, 4),
((select id from c), 'Lassi', NULL, 245.00, true, 5),
((select id from c), 'Avocado Kachumber', NULL, 395.00, true, 6),
((select id from c), 'Garlic Bread', NULL, 425.00, true, 7),
((select id from c), 'Cheese Garlic Bread', NULL, 425.00, true, 8);

with c as (insert into menu_categories (name, slug, sort_order) values ('Desserts', 'desserts', 22) returning id)
insert into menu_items (category_id, name, description, price, is_veg, sort_order) values
((select id from c), 'Shahi Tukda Dippers', NULL, 545.00, true, 0),
((select id from c), 'Ice Cream Sundae', NULL, 555.00, true, 1),
((select id from c), 'Hot Chocolate Brownie', NULL, 565.00, true, 2),
((select id from c), 'Brûlée Phirni', NULL, 575.00, true, 3),
((select id from c), 'Biscoff Banoffee Pie', NULL, 575.00, true, 4),
((select id from c), 'Carrot Halwa Cake', NULL, 575.00, true, 5),
((select id from c), 'Gulab Jamun Tres Leche', NULL, 595.00, true, 6),
((select id from c), 'Banjara Tiramisu', NULL, 625.00, true, 7);

with c as (insert into menu_categories (name, slug, sort_order) values ('Iced Teas', 'iced-teas', 23) returning id)
insert into menu_items (category_id, name, description, price, is_veg, sort_order) values
((select id from c), 'Kafir Lime & Lemongrass', NULL, 325.00, true, 0),
((select id from c), 'Peach & Basil', NULL, 325.00, true, 1),
((select id from c), 'Kahwa', 'Kashmiri spices, almond honey', 345.00, true, 2),
((select id from c), 'Orange', 'Elderflower Syrup', 345.00, true, 3),
((select id from c), 'Lavender', NULL, 345.00, true, 4),
((select id from c), 'Hibiscus', 'Ginger slice, orange', 365.00, true, 5);

with c as (insert into menu_categories (name, slug, sort_order) values ('Signature Mocktails', 'signature-mocktails', 24) returning id)
insert into menu_items (category_id, name, description, price, is_veg, sort_order) values
((select id from c), 'Mumbai Mango', 'Coconut rum, pina colada, Mango syrup', 335.00, true, 0),
((select id from c), 'Apple Lime Ice', 'Apple crush, vanilla lime squash', 335.00, true, 1),
((select id from c), 'V. Mojito', 'Spanish Shrubs, mint, lime, sugar syrup', 335.00, true, 2),
((select id from c), 'V. Marry', 'Sun Dried Chilli Black Pepper, lime Juice, habanero bitters', 335.00, true, 3),
((select id from c), 'The Refresher', 'Kiwi Mango, lemon Rose, Jalapeño, citric foam', 335.00, true, 4),
((select id from c), 'Redi', 'Cranberry, Ginger, Grenadine, Pomegranate', 335.00, true, 5),
((select id from c), 'Kashmiri Cooler', 'Elderflower, Rose Hibiscus, cardamom, Saffron syrup, lime juice', 345.00, true, 6),
((select id from c), 'Tovelo', 'Fresh Coconut, Pineapple, Black Lime', 345.00, true, 7),
((select id from c), 'V. Lagoon', 'Blue curacao, lime juice, blue lagoon sprite', 335.00, true, 8),
((select id from c), 'Tropical Sunrise', 'Orange Juice, Pineapple, coke', 345.00, true, 9),
((select id from c), 'Thai High', 'Sweet Lychee, Jasmine both citrus iced, Ginger Ale', 345.00, true, 10),
((select id from c), 'Blueberry Mule', 'Fresh Blueberry Mint, Ginger Syrup, Top up Ginger Ale', 355.00, true, 11),
((select id from c), 'Tropical C', 'Passionfruit, Pineapple Juice, Jasmine', 355.00, true, 12),
((select id from c), 'Beach Break', 'Pineapple, Yuzu Essence, Coconut Cream', 355.00, true, 13),
((select id from c), 'Seeds of Life', 'Fresh Passion, Lime Juice, Mint Basil Syrup', 455.00, true, 14),
((select id from c), 'Melon Fantasy', 'Fresh Watermelon, Citric Juice, cranberry Syrup', 485.00, true, 15),
((select id from c), 'Smooth Operator', 'Fresh Pineapple, Cucumber Mint, Yuzu Mist, Mint and Citrus Syrup, Lime and Sugar Syrup', 495.00, true, 16);

with c as (insert into menu_categories (name, slug, sort_order) values ('Banjara Lemonades', 'banjara-lemonades', 25) returning id)
insert into menu_items (category_id, name, description, price, is_veg, sort_order) values
((select id from c), 'Classic', NULL, 275.00, true, 0),
((select id from c), 'Coconut', NULL, 285.00, true, 1),
((select id from c), 'Rose', NULL, 285.00, true, 2),
((select id from c), 'Mango', NULL, 295.00, true, 3),
((select id from c), 'Berry', NULL, 305.00, true, 4);

with c as (insert into menu_categories (name, slug, sort_order) values ('Indian Estate Coffee', 'indian-estate-coffee', 26) returning id)
insert into menu_items (category_id, name, description, price, is_veg, sort_order) values
((select id from c), 'Americano', NULL, 175.00, true, 0),
((select id from c), 'House Blend Cold Brew on Ice', NULL, 185.00, true, 1),
((select id from c), 'Espresso', NULL, 195.00, true, 2),
((select id from c), 'Lungo / Cappuccino / Flat White', NULL, 205.00, true, 3),
((select id from c), 'Latte / Mocha', NULL, 215.00, true, 4),
((select id from c), 'Espresso & Tonic with Orange Slice', NULL, 215.00, true, 5),
((select id from c), 'Affogato / Condensed Milk', NULL, 215.00, true, 6),
((select id from c), 'Hot Chocolate / Vanilla & Cinnamon', NULL, 225.00, true, 7),
((select id from c), 'Macchiato / Cortado', NULL, 205.00, true, 8),
((select id from c), 'Iced Americano', NULL, 225.00, true, 9),
((select id from c), 'Iced Mocha', NULL, 245.00, true, 10),
((select id from c), 'Classic Cold Coffee', NULL, 299.00, true, 11),
((select id from c), 'Frappe', 'Ice Coffee and Milk', 305.00, true, 12),
((select id from c), 'Mocha Frappe', 'Ice Cream, Chocolate Milk and Coffee', 365.00, true, 13),
((select id from c), 'Indulgend Cold Coffee', 'Ice Cream, Coffee with Chocolate and Whipped Cream', 399.00, true, 14),
((select id from c), 'Add Ons', 'Extra Espresso Shot / Flavour Syrup', 75.00, true, 15);

with c as (insert into menu_categories (name, slug, sort_order) values ('Cold Pressed Juices', 'cold-pressed-juices', 27) returning id)
insert into menu_items (category_id, name, description, price, is_veg, sort_order) values
((select id from c), 'Orange / Pineapple / Watermelon / Sweet Lime', 'Range ₹285–295', 285.00, true, 0),
((select id from c), 'One for the Soul', 'Sugarcane, Ginger, Lime, Mint', 275.00, true, 1),
((select id from c), 'Heart Beet', 'Apple, Beetroot, Carrot, Amla', 305.00, true, 2),
((select id from c), 'Rainbow', 'Orange, Sweet Lime, Basil, Chilli, Stevia', 305.00, true, 3),
((select id from c), 'Drink Your Greens', 'Spinach, Celery, Cucumber, Green Apple', 315.00, true, 4),
((select id from c), 'Tropical Sunshine', 'Pineapple, Lemon, Ginger, Honey, Tea', 325.00, true, 5);

with c as (insert into menu_categories (name, slug, sort_order) values ('Smoothies', 'smoothies', 28) returning id)
insert into menu_items (category_id, name, description, price, is_veg, sort_order) values
((select id from c), 'Monkey', 'Dark Chocolate, Peanut Butter, Banana, Dates', 365.00, true, 0),
((select id from c), 'Skinny Berry', 'Strawberry, Blueberry, Raspberry, Basil', 365.00, true, 1),
((select id from c), 'Green Monster', 'Green Apple, Kiwi, Spinach, Vanilla', 365.00, true, 2);

with c as (insert into menu_categories (name, slug, sort_order) values ('Thick Shakes', 'thick-shakes', 29) returning id)
insert into menu_items (category_id, name, description, price, is_veg, sort_order) values
((select id from c), 'Masala Chai Latte', 'Masala, Chai, Masala Tea, Whipped Caramel', 355.00, true, 0),
((select id from c), 'Cinnamon Cold Coffee', 'Vanilla Ice Cream, Coffee, Caramel Cinnamon', 365.00, true, 1),
((select id from c), 'S''mores Milkshake', 'Marshmallow Cream, Malt Milk, Chocolate Cream, Biscuit Crumbs', 375.00, true, 2),
((select id from c), 'Old School Strawberry Milkshake', 'Strawberry Ice Cream, Strawberry Chutney, Vanilla Shake', 375.00, true, 3),
((select id from c), 'Oreo Cheesecake Milkshake', 'Vanilla Ice Cream, Oreo''s, Cheesecake, Whipped Caramel Cream', 395.00, true, 4),
((select id from c), 'Caramel Paradise', 'Toffee Biscuits, Toffee Sauce, Toffee Crumb', 415.00, true, 5);

commit;